# Generated by Django 6.0.3 on 2026-03-18 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_names', models.CharField(max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('guests_expected', models.IntegerField(default=0)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('style', models.CharField(choices=[('classico', 'Clássico'), ('rustico', 'Rústico'), ('moderno', 'Moderno'), ('luxo', 'Luxo')], default='classico', max_length=20)),
                ('ceremony_time', models.TimeField(default='16:00')),
                ('party_time', models.TimeField(default='18:00')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
