# Generated by Django 6.0.3 on 2026-03-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meu Evento', max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Casamento'), ('corporate', 'Corporativo'), ('birthday', 'Aniversário'), ('party', 'Festa'), ('other', 'Outro')], default='wedding', max_length=20)),
                ('theme', models.CharField(choices=[('classic', 'Clássico'), ('modern', 'Moderno'), ('rustic', 'Rústico'), ('beach', 'Praia'), ('garden', 'Jardim'), ('tech', 'Tecnologia'), ('hawaiian', 'Havaiano'), ('vintage', 'Vintage'), ('minimalist', 'Minimalista'), ('luxury', 'Luxo'), ('custom', 'Personalizado')], default='classic', max_length=50)),
                ('custom_theme', models.CharField(blank=True, help_text='Se tema for personalizado, descreva aqui', max_length=255)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('guests_expected', models.IntegerField(default=0)),
                ('couple_names', models.CharField(blank=True, help_text='Para casamentos', max_length=255)),
                ('company_name', models.CharField(blank=True, help_text='Para eventos corporativos', max_length=255)),
                ('start_time', models.TimeField(default='18:00')),
                ('end_time', models.TimeField(default='00:00')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
